### ISSUE TITLE
I have no environment to run it

### ISSUE THREAD

**Issue by qfxdz** [tesslerc/H-DRLN#1]
hello, I want to run it,but I don't know what the parameters mean,and I seem to be missing something. Can you help me? thanks.

**Comment by tesslerc** [comment]
The environment at the time was built on top of Burlapcraft, a mod for Minecraft.
Unfortunately, we did not upload the code at the time, and as this is a very old project, we do not have those files anymore.

I suggest you take a look at project Malmo for a Minecraft environment, and implementing the H-DRLN using PyTorch / TensorFlow shouldn't be too complex (I'll gladly help iron out some details if needed).

**Comment by qfxdz** [comment]
Thank you. I will try.( I think it's a very good study.)
How can I contact you if I have any questions?Can I contact you by Email?

**Comment by tesslerc** [comment]
Sure, by email is fine.
